import type { Tenant, TenantFeaturePermissions, RolePermissions, ServiceCategory } from './types';
import { MembershipApprovalMode, TenantRoleType } from './types';

export const SERVICE_CATEGORY_OPTIONS: { value: ServiceCategory; label: string; description: string }[] = [
  { value: 'CEREMONY', label: 'Ceremonies', description: 'Weddings, funerals, baptisms, dedications' },
  { value: 'EDUCATION', label: 'Education', description: 'Classes, courses, Sunday school, discipleship' },
  { value: 'FACILITY', label: 'Facilities', description: 'Space rentals, banquets, events, rehearsals' },
  { value: 'COUNSELING', label: 'Counseling', description: 'Pastoral care, marriage counseling, mentoring' },
  { value: 'OTHER', label: 'Other', description: 'Community services, outreach, unique offerings' },
];

export const CONTROL_PANEL_TABS = [
  'General',
  'Branding',
  'Features',
  'Permissions',
  'Membership & Moderation',
  'User Profiles',
  'Donations',
  'Volunteering',
  'Small Groups',
  'Services',
  'Facilities',
  'Live Stream',
  'Prayer Wall',
  'Resource Center',
  'Contact Submissions',
  'Trips',
].sort((a, b) => a.localeCompare(b));

const defaultRolePermissions: RolePermissions = {
  canCreatePosts: false,
  canCreateEvents: false,
  canCreateSermons: false,
  canCreatePodcasts: false,
  canCreateBooks: false,
  canCreateGroupChats: false,
  canInviteMembers: false,
  canApproveMembership: false,
  canBanMembers: false,
  canModeratePosts: false,
  canModerateChats: false,
  canPostInAnnouncementChannels: false,
  canManagePrayerWall: false,
  canUploadResources: false,
  canManageResources: false,
  canManageContactSubmissions: false,
  canManageFacilities: false,
};

export const adminPermissions: RolePermissions = {
  canCreatePosts: true,
  canCreateEvents: true,
  canCreateSermons: true,
  canCreatePodcasts: true,
  canCreateBooks: true,
  canCreateGroupChats: true,
  canInviteMembers: true,
  canApproveMembership: true,
  canBanMembers: true,
  canModeratePosts: true,
  canModerateChats: true,
  canPostInAnnouncementChannels: true,
  canManagePrayerWall: true,
  canUploadResources: true,
  canManageResources: true,
  canManageContactSubmissions: true,
  canManageFacilities: true,
};

const defaultPermissions: TenantFeaturePermissions = {
  [TenantRoleType.MEMBER]: {
    ...defaultRolePermissions,
    canCreatePosts: true,
    canUploadResources: true, // Allow members to upload resources by default
  },
  [TenantRoleType.STAFF]: {
    ...defaultRolePermissions,
    canCreatePosts: true,
    canCreateEvents: true,
    canCreateSermons: true,
    canInviteMembers: true,
    canModeratePosts: true,
    canModerateChats: true,
    canPostInAnnouncementChannels: true,
    canManagePrayerWall: true,
    canUploadResources: true,
    canManageResources: true,
    canManageContactSubmissions: true,
    canManageFacilities: true,
  },
  [TenantRoleType.MODERATOR]: {
    ...defaultRolePermissions,
    canModeratePosts: true,
    canModerateChats: true,
    canApproveMembership: true,
    canBanMembers: true,
    canManagePrayerWall: true,
    canManageResources: true, // Moderators can manage resources
    canManageFacilities: false,
  },
  ADMIN: {
    ...adminPermissions,
  },
};


export const getInitialTenant = (): Omit<Tenant, 'id' | 'name' | 'slug' | 'creed' | 'address' | 'description'> => ({
  settings: {
    isPublic: true,
    membershipApprovalMode: MembershipApprovalMode.OPEN,
    enableCalendar: true,
    enablePosts: true,
    enableSermons: true,
    enablePodcasts: false,
    enablePhotos: true,
    enableBooks: false,
    enableMemberDirectory: true,
    enableGroupChat: true,
    enableComments: true,
    enableReactions: true,
    enableServices: true,
    enableDonations: false,
    enableVolunteering: true,
    enableSmallGroups: true,
    enableTrips: false,
    enableLiveStream: false,
    enablePrayerWall: false,
    autoApprovePrayerWall: false,
    enableResourceCenter: false,
    enableTripFundraising: false,
    tripCalendarColor: '#0EA5E9',
    donationSettings: {
      mode: 'EXTERNAL',
      externalUrl: '',
      currency: 'USD',
      suggestedAmounts: [5, 10, 25, 50, 100],
      allowCustomAmounts: true,
      leaderboardEnabled: false,
      leaderboardVisibility: 'MEMBERS_ONLY',
      leaderboardTimeframe: 'ALL_TIME',
      paypalUrl: '',
      venmoHandle: '',
      zelleEmail: '',
      cashAppTag: '',
      mailingAddress: '',
      taxId: '',
      bankTransferInstructions: '',
      textToGiveNumber: '',
      otherGivingNotes: '',
      otherGivingLinks: [],
    },
    liveStreamSettings: {
        provider: 'YOUTUBE',
        embedUrl: '',
        isLive: false,
    },
    visitorVisibility: {
      calendar: true,
      posts: true,
      sermons: true,
      podcasts: false,
      photos: false,
      books: false,
      prayerWall: false,
    },
  },
  branding: {
    logoUrl: '',
    bannerImageUrl: '',
    primaryColor: '#8B5CF6', // A warm purple
    accentColor: '#F59E0B', // A warm amber
    customLinks: [],
  },
  permissions: defaultPermissions,
});
