@echo off
echo Starting development server...
start "Next.js Dev Server" cmd /c "npm run dev"

echo Waiting for the server to start...
timeout /t 10 /nobreak > nul

echo Opening Chrome...
start chrome http://localhost:3000
