export type ChannelDef = { name: string; type: 'public' | 'private' };
export type UserArchetype = {
  displayName: string;
  email: string;
  bio: string;
  traits: string[];
  attitude: string;
};

export type TenantDef = {
  name: string;
  slug: string;
  description: string;
  logoUrl: string;
  bannerUrl: string;
  channels: ChannelDef[];
  users: UserArchetype[];
};

// Deterministic placeholder helpers (pattern-based URLs)
// Use DiceBear v6+ API (stable, versioned) and return SVG which is reliable in browsers.
const avatar = (seed: string) => `https://api.dicebear.com/6.x/adventurer/svg?seed=${encodeURIComponent(seed)}&size=200`;
const photo = (seed: string) => `https://picsum.photos/seed/${encodeURIComponent(seed)}/200/200`;
const banner = (text: string) => `https://placehold.co/1200x200/222222/ffffff?text=${encodeURIComponent(text)}`;

// Helper to build 20 user archetypes quickly
function buildUsers(slug: string, locals: Array<[string,string,string,string[]]>) {
  return locals.map((entry, idx) => {
    const [local, displayName, bio, traitsCsv] = entry;
    const email = `${local}@${slug}.example`;
    return {
      displayName,
      email,
      bio,
      traits: traitsCsv,
      attitude: 'Friendly and engaged',
    };
  });
}

export const TENANTS: TenantDef[] = [
  {
    name: 'Springfield Community Fellowship',
    slug: 'springfield-community',
    description: 'Small-town fellowship emphasizing neighborly outreach, lively potlucks, and community care.',
    logoUrl: avatar('springfield-community'),
    bannerUrl: banner('Springfield Community Fellowship Banner'),
    channels: [
      { name: 'Announcements', type: 'public' },
      { name: 'Prayer Wall', type: 'public' },
      { name: 'Pastoral Team', type: 'private' },
      { name: 'Youth Group', type: 'private' },
      { name: 'Volunteer Coordination', type: 'private' },
    ],
    users: [
      { displayName: 'Homer J. Simpson', email: 'homer@springfield.example', bio: 'Safety inspector, donut aficionado, and proud owner of a finely tuned groan — frequently heard: "D\'oh!"', traits: ['lovable','bumbling','hungry'], attitude: 'Goofy and well-meaning' },
      { displayName: 'Marge Simpson', email: 'marge@springfield.example', bio: 'Patient, resourceful, and the glue that holds an occasionally combustible family together. Blue beehive extraordinaire.', traits: ['steady','kind','organised'], attitude: 'Calm and practical' },
      { displayName: 'Bart Simpson', email: 'bart@springfield.example', bio: 'Ten-year-old prank artist, skateboard enthusiast, and general mischief merchant. Catchphrase: "Eat my shorts!"', traits: ['mischievous','bold','clever'], attitude: 'Playful troublemaker' },
      { displayName: 'Lisa Simpson', email: 'lisa@springfield.example', bio: 'Young intellectual, saxophonist, and passionate activist — often the voice of reason in the family.', traits: ['curious','principled','brilliant'], attitude: 'Thoughtful and earnest' },
      { displayName: 'Ned Flanders', email: 'ned@springfield.example', bio: 'Friendly neighbor, devout community member, and small-business owner — okily-dokily all the way.', traits: ['cheerful','helpful','faithful'], attitude: 'Sunny and supportive' },
      { displayName: 'Moe Szyslak', email: 'moe@springfield.example', bio: 'Grumpy tavern-keeper with a soft spot for the regulars and a long list of questionable business plans.', traits: ['gruff','loyal','cynical'], attitude: 'Dry and world-weary' },
      { displayName: 'Apu Nahasapeemapetilon', email: 'apu@springfield.example', bio: 'Diligent Kwik-E-Mart proprietor, student of Bengali pop culture, and community pillar (with a fondness for the Squishee).', traits: ['hardworking','witty','entrepreneurial'], attitude: 'Warm and pragmatic' },
      { displayName: 'Chief Clancy Wiggum', email: 'wiggum@springfield.example', bio: 'Police chief with a love for donuts, surprising gullibility, and heroic instincts when it counts.', traits: ['goofy','endearing','scatterbrained'], attitude: 'Lovably incompetent' },
      { displayName: 'Lenny Leonard', email: 'lenny@springfield.example', bio: 'Longtime friend and coworker who can always be counted on for a laugh and an extra helping of camaraderie.', traits: ['loyal','easygoing','funny'], attitude: 'Affable and steady' },
      { displayName: 'Carl Carlson', email: 'carl@springfield.example', bio: 'Homer\'s pragmatic friend, low-key philosopher, and occasional voice of reason in the break room.', traits: ['grounded','witty','steady'], attitude: 'Laid-back and clever' },
      { displayName: 'Milhouse Van Houten', email: 'milhouse@springfield.example', bio: 'Bart\'s best friend — earnest, unlucky in love, and a dedicated sidekick to chaotic plans.', traits: ['loyal','naive','hopeful'], attitude: 'Eager and plaintive' },
      { displayName: 'Edna Krabappel', email: 'edna@springfield.example', bio: 'Seasoned elementary school teacher with sharp sarcasm and a hidden romantic streak (subtle eye-rolls included).', traits: ['savvy','wry','dedicated'], attitude: 'Dryly candid' },
      { displayName: 'Professor Frink', email: 'frink@springfield.example', bio: 'Scientist-inventor known for improbable inventions and a delightfully eccentric lexicon.', traits: ['brilliant','quirky','inventive'], attitude: 'Enthusiastically nerdy' },
      { displayName: 'Patty Bouvier', email: 'patty@springfield.example', bio: 'Hard-nosed, chain-smoking sister with an eye for hypocrisy and the occasional dry laugh.', traits: ['sardonic','direct','tough'], attitude: 'World-weary and frank' },
      { displayName: 'Selma Bouvier', email: 'selma@springfield.example', bio: 'Tough as nails and twice as stubborn — works at the DMV and collects ex-husbands like souvenirs.', traits: ['gritty','practical','sardonic'], attitude: 'Blunt and comedic' },
      { displayName: 'Comic Book Guy', email: 'comicguy@springfield.example', bio: 'Keeper of pop-culture opinion, proud denizen of the Android\'s Dungeon — fiercely loyal to his fandoms.', traits: ['opinionated','obsessive','funny'], attitude: 'Snarky and passionate' },
      { displayName: 'Platform Admin', email: 'admin@springfield.example', bio: 'Local site admin and resident moderator for Springfield tenant content.', traits: ['helpful','organized','omniscient'], attitude: 'Authoritative and kind' },
    ],

    // Add a vivid Game of Thrones / A Song of Ice and Fire tenant based on book characters
  },

  {
    name: 'A Song of Ice & Fire Fellowship',
    slug: 'game-of-thrones',
    description: 'A fellowship for readers and roleplayers of the world of Westeros and beyond — lore nights, costume workshops, and debate halls.',
    logoUrl: avatar('game-of-thrones'),
    bannerUrl: banner('A Song of Ice & Fire Fellowship Banner'),
    channels: [
      { name: 'Announcements', type: 'public' },
      { name: 'Lore Nights', type: 'public' },
      { name: 'House Halls', type: 'private' },
      { name: 'Costume Workshop', type: 'public' },
      { name: 'Moderation', type: 'private' },
    ],
    users: [
      { displayName: 'Eddard Stark', email: 'ned@westeros.example', bio: 'Lord of Winterfell; steady, honour-bound leader who values duty above all.', traits: ['honourable','steadfast','serious'], attitude: 'Stoic and fair' },
      { displayName: 'Catelyn Stark', email: 'catelyn@westeros.example', bio: 'Matriarch of House Stark; protective, politically observant, and fiercely devoted to family.', traits: ['protective','strategic','eloquent'], attitude: 'Resolute and measured' },
      { displayName: 'Robb Stark', email: 'robb@westeros.example', bio: 'Young commander and charismatic leader; earnest and quick to defend his people.', traits: ['brave','impulsive','loyal'], attitude: 'Valorous and direct' },
      { displayName: 'Sansa Stark', email: 'sansa@westeros.example', bio: 'Learns the language of courts; patient and politically savvy in formation.', traits: ['observant','graceful','patient'], attitude: 'Poised and thoughtful' },
      { displayName: 'Arya Stark', email: 'arya@westeros.example', bio: 'Independent, resourceful, and surprisingly blunt — a doer rather than a talker.', traits: ['fierce','curious','practical'], attitude: 'Wry and purposeful' },
      { displayName: 'Bran Stark', email: 'bran@westeros.example', bio: 'Quiet observer with strange insights into history and memory.', traits: ['reflective','mysterious','insightful'], attitude: 'Serene and distant' },
      { displayName: 'Jon Snow', email: 'jon@westeros.example', bio: 'Raised at Winterfell; honorable, quietly brooding, and devoted to those he leads.', traits: ['honourable','reserved','resolute'], attitude: 'Measured and earnest' },
      { displayName: 'Tyrion Lannister', email: 'tyrion@westeros.example', bio: 'Clever, well-read, and witty — wields words like weapons when needed.', traits: ['witty','learned','pragmatic'], attitude: 'Clever and sardonic' },
      { displayName: 'Cersei Lannister', email: 'cersei@westeros.example', bio: 'Formidable political actor; always calculating and protective of her power.', traits: ['ruthless','political','ambitious'], attitude: 'Sharp and determined' },
      { displayName: 'Jaime Lannister', email: 'jaime@westeros.example', bio: 'Complex warrior with a reputation and a layered sense of duty.', traits: ['skilled','conflicted','honourable'], attitude: 'Guarded and earnest' },
      { displayName: 'Daenerys Targaryen', email: 'daenerys@westeros.example', bio: 'Charismatic leader of ideas and dragons; passionate about justice and change.', traits: ['determined','charismatic','visionary'], attitude: 'Fierce and inspirational' },
      { displayName: 'Stannis Baratheon', email: 'stannis@westeros.example', bio: 'Steadfast claimant with rigid principles and an unyielding sense of duty.', traits: ['unyielding','stern','commanding'], attitude: 'Severe and principled' },
      { displayName: 'Melisandre', email: 'melisandre@westeros.example', bio: 'Mysterious priestess with strong conviction and an affinity for prophecy.', traits: ['mystical','devout','enigmatic'], attitude: 'Intense and visionary' },
      { displayName: 'Petyr Baelish', email: 'petyr@westeros.example', bio: 'A manipulative courtier whose networks of favors and whispers keep him influential.', traits: ['scheming','clever','smooth'], attitude: 'Suave and observant' },
      { displayName: 'Varys', email: 'varys@westeros.example', bio: 'Master of whispers; quietly collects information to shape outcomes across the realms.', traits: ['calm','informative','patient'], attitude: 'Measured and cryptic' },
      { displayName: 'Samwell Tarly', email: 'samwell@westeros.example', bio: 'Scholar at heart; diligent reader, loyal friend, and keeper of arcane knowledge.', traits: ['scholarly','gentle','curious'], attitude: 'Warm and inquisitive' },
      { displayName: 'Brienne of Tarth', email: 'brienne@westeros.example', bio: 'Honour-bound warrior; steadfast protector and exemplar of quiet bravery.', traits: ['honourable','steadfast','noble'], attitude: 'Earnest and loyal' },
      { displayName: 'Jorah Mormont', email: 'jorah@westeros.example', bio: 'Exiled knight seeking redemption; loyal beyond reason and knowledgeable about many shores.', traits: ['loyal','seasoned','melancholic'], attitude: 'Sincere and wary' },
      { displayName: 'Theon Greyjoy', email: 'theon@westeros.example', bio: 'A troubled soul searching for identity and acceptance among conflicting loyalties.', traits: ['restless','contrite','complex'], attitude: 'Torn and candid' },
      { displayName: 'Davos Seaworth', email: 'davos@westeros.example', bio: 'Practical hand and honest counselor; pragmatic with a moral compass.', traits: ['practical','steady','humble'], attitude: 'Grounded and earnest' },
      { displayName: 'Margaery Tyrell', email: 'margaery@westeros.example', bio: 'Political charm and social grace; adept at winning hearts and alliances.', traits: ['charming','strategic','gracious'], attitude: 'Warmly strategic' },
      { displayName: 'Olenna Tyrell', email: 'olenna@westeros.example', bio: 'Keen-witted matriarch with a sharp tongue and a softer agenda for her house.', traits: ['sharp','witty','formidable'], attitude: 'Savage and humorous' },
    ],
  },

  {
    name: 'Northbridge Fellowship',
    slug: 'northbridge-fellowship',
    description: 'A fellowship styled around feudal-era storytelling groups — roleplay-friendly discussion spaces, councils, and lore-reading circles.',
    logoUrl: avatar('northbridge-fellowship'),
    bannerUrl: banner('Northbridge Fellowship Banner'),
    channels: [
      { name: 'Court Announcements', type: 'public' },
      { name: 'Lore Council', type: 'private' },
      { name: 'Adventurers', type: 'public' },
      { name: 'Scriptorium', type: 'public' },
      { name: 'Moderators', type: 'private' },
    ],
    users: [
      { displayName: 'Lord Edmund Blackthorne', email: 'edmund@northbridge.example', bio: 'A silver-tongued speaker who loves a good council and finer rhetoric — collects quills and clever retorts.', traits: ['articulate','ambitious','witty'], attitude: 'Orator and showman' },
      { displayName: 'Elinor Scribewell', email: 'elinor@northbridge.example', bio: 'Archivist and scribe, cataloging every scroll and rumor with a tidy hand and a conspiratorial smile.', traits: ['studious','meticulous','observant'], attitude: 'Quietly obsessive' },
      { displayName: 'Captain Rowan', email: 'rowan@northbridge.example', bio: 'Battle-hardened knight and organizer of the LARP tournaments — firm with a secret love of poetry.', traits: ['disciplined','brave','fair'], attitude: 'Commanding but kind' },
      { displayName: 'Maris Bannerwood', email: 'maris@northbridge.example', bio: 'Artisan of banners and heraldry; her designs are half art, half history lesson.', traits: ['creative','proud','precise'], attitude: 'Proud craftsperson' },
      { displayName: 'Bram Tavendale', email: 'bram@northbridge.example', bio: 'Innkeeper and social glue; his hearth knows everyone and his stew wins hearts.', traits: ['genial','hospitable','gregarious'], attitude: 'Warm raconteur' },
      { displayName: 'Lorekeeper Hester', email: 'hester@northbridge.example', bio: 'Loves dusty tomes and obscure footnotes — will happily debate the provenance of any legend.', traits: ['curious','obsessive','talkative'], attitude: 'Enthusiastic scholar' },
      { displayName: 'Finn Scoutwind', email: 'finn@northbridge.example', bio: 'Trail leader who scouts meetups and maps the wilds; brings biscuits and bad jokes.', traits: ['adventurous','alert','friendly'], attitude: 'Practical and upbeat' },
      { displayName: 'Maven the Scholar', email: 'maven@northbridge.example', bio: 'Quiet researcher working through tomes and translation projects in the scriptorium.', traits: ['analytical','patient','introverted'], attitude: 'Solemn and curious' },
      { displayName: 'Gideon Ironhand', email: 'gideon@northbridge.example', bio: 'Blacksmith and prop-maker who turns ideas into armor and occasionally dramatic hats.', traits: ['hands-on','practical','patient'], attitude: 'Solid and good-humored' },
      { displayName: 'Tom Squire', email: 'tom@northbridge.example', bio: 'Young squire learning the ropes; eager to help and always covered in sawdust.', traits: ['eager','clumsy','loyal'], attitude: 'Bright and determined' },
      { displayName: 'Amara the Healer', email: 'amara@northbridge.example', bio: 'Herbalist and first-aid lead — she can tidy a prop wound and a bruised ego in equal measure.', traits: ['caring','knowledgeable','calm'], attitude: 'Gentle pragmatist' },
      { displayName: 'Owen Gateward', email: 'owen@northbridge.example', bio: 'Stern gatekeeper who keeps events orderly and offers wry commentary on the antics he sees.', traits: ['firm','fair','no-nonsense'], attitude: 'Dry and fair' },
      { displayName: 'Lys Bardwell', email: 'lys@northbridge.example', bio: 'Bard with a talent for satire; will set your deeds to a jaunty tune.', traits: ['charismatic','witty','sensitive'], attitude: 'Performative and sharp' },
      { displayName: 'Maera Archivist', email: 'maera@northbridge.example', bio: 'Organizes scrolls and keeps minutes — nothing escapes her index.', traits: ['methodical','organized','patient'], attitude: 'Quietly proud' },
      { displayName: 'Isadore Merchant', email: 'isadore@northbridge.example', bio: 'Trader and swap-meet curator — always with an eye for a useful oddity.', traits: ['shrewd','sociable','helpful'], attitude: 'Shrewd but generous' },
      { displayName: 'Rowena Roadward', email: 'rowena@northbridge.example', bio: 'Leads outreach and roadside aid with a steady laugh and a wagon of supplies.', traits: ['humble','reliable','generous'], attitude: 'Down-to-earth helper' },
      { displayName: 'Nell Costumewright', email: 'nell@northbridge.example', bio: 'Costume designer obsessed with historically plausible pockets and dramatic hems.', traits: ['creative','exacting','playful'], attitude: 'Perfectionist with flair' },
      { displayName: 'Moderator Lead', email: 'moderator@northbridge.example', bio: 'Keeps debates civil and ensures everyone gets a turn at the dais.', traits: ['calm','authoritative','fair'], attitude: 'Balanced and diplomatic' },
      { displayName: 'New Participant', email: 'new@northbridge.example', bio: 'Curious newcomer exploring swordcraft and library stacks for the first time.', traits: ['curious','tentative','polite'], attitude: 'Excited and polite' },
    ],
  },

  {
    name: 'St. Marianne Parish',
    slug: 'st-marianne-parish',
    description: 'Traditional parish with liturgical calendar, sacraments scheduling, pastoral care, and outreach ministries.',
    logoUrl: avatar('st-marianne-parish'),
    bannerUrl: banner('St. Marianne Parish Banner'),
    channels: [
      { name: 'Parish Announcements', type: 'public' },
      { name: 'Liturgy Team', type: 'private' },
      { name: 'Outreach Ministry', type: 'public' },
      { name: 'Youth Ministry', type: 'private' },
      { name: 'Prayer Requests', type: 'public' },
    ],
    users: [
      { displayName: 'Father Miguel O\'Connor', email: 'miguel@st-marianne.example', bio: 'Parish priest with a warm laugh and a well-worn Bible — known for thoughtful homilies and excellent coffee hour banter.', traits: ['pastoral','steady','compassionate'], attitude: 'Pastoral and kind' },
      { displayName: 'Mary Katherine Delaney', email: 'marykatherine@st-marianne.example', bio: 'Head of small groups and sacristy volunteer; organizes bake sales with military precision and an eye for hymn arrangement.', traits: ['organised','charismatic','gracious'], attitude: 'Welcoming traditionalist' },
      { displayName: 'Deacon Thomas Reed', email: 'thomas@st-marianne.example', bio: 'Dutiful deacon with a love for sacramental detail and the parish bulletin.', traits: ['service-minded','steady','dependable'], attitude: 'Quietly faithful' },
      { displayName: 'Sister Agnes Lopez', email: 'agnes@st-marianne.example', bio: 'Religious educator who runs the catechism classes and brings inexhaustible patience and cookies.', traits: ['patient','wise','nurturing'], attitude: 'Stern but loving' },
      { displayName: 'Liam O\'Sullivan', email: 'liam@st-marianne.example', bio: 'Choir director who can make a congregation sound like an angelic army — compassionate with a conductor\'s glare.', traits: ['musical','meticulous','encouraging'], attitude: 'Passionate and exact' },
      { displayName: 'Rosa Martinez', email: 'rosa@st-marianne.example', bio: 'Community outreach lead who connects the parish to local shelters and organizes cultural liturgies.', traits: ['generous','practical','inclusive'], attitude: 'Energetic bridge-builder' },
      { displayName: 'Peter Grant', email: 'peter@st-marianne.example', bio: 'Facilities manager who knows which pew creaks and how to keep the heating polite.', traits: ['practical','reliable','hands-on'], attitude: 'Dryly competent' },
      { displayName: 'Anna Park', email: 'anna@st-marianne.example', bio: 'Sunday school coordinator who remembers every child\'s name and favourite craft glue.', traits: ['warm','organized','patient'], attitude: 'Maternal and efficient' },
      { displayName: 'Evelyn Harper', email: 'evelyn@st-marianne.example', bio: 'Parish council chair with a keen sense for tradition and a talent for spreadsheets.', traits: ['strategic','thoughtful','civic-minded'], attitude: 'Measured and firm' },
      { displayName: 'Youth Leader Caleb', email: 'caleb@st-marianne.example', bio: 'Leads youth nights with energetic playlists and philosophical conversation starters.', traits: ['energetic','engaging','encouraging'], attitude: 'Fun and earnest' },
      { displayName: 'Grace Abbott', email: 'grace@st-marianne.example', bio: 'Hospitality host who takes tea and fellowship seriously and brings cookies to every meeting.', traits: ['welcoming','practical','cheerful'], attitude: 'Warm and hospitable' },
      { displayName: 'Elder Joan', email: 'joan@st-marianne.example', bio: 'Longtime parishioner and memory-keeper; she knows every hymn by heart and every church story.', traits: ['nostalgic','wise','steady'], attitude: 'Fond and steady' },
      { displayName: 'Finance Officer Mark', email: 'mark@st-marianne.example', bio: 'Manages donations and budgets with calm precision and a soft smile.', traits: ['trustworthy','detail-oriented','pragmatic'], attitude: 'Practical steward' },
      { displayName: 'New Parishioner Lily', email: 'lily@st-marianne.example', bio: 'Recently arrived and curious about the rituals; likes to linger after services for conversation.', traits: ['curious','grateful','tentative'], attitude: 'Warmly inquisitive' },
      { displayName: 'Platform Admin', email: 'admin@st-marianne.example', bio: 'Site admin and moderator for the parish community.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive administrator' },
    ],
  },

  {
    name: 'Riverbend Baptist Church',
    slug: 'riverbend-baptist',
    description: 'Community-focused evangelical church with robust volunteer teams and outreach programs.',
    logoUrl: avatar('riverbend-baptist'),
    bannerUrl: banner('Riverbend Baptist Banner'),
    channels: [
      { name: 'Weekly Bulletin', type: 'public' },
      { name: 'Missions', type: 'public' },
      { name: 'Deacons', type: 'private' },
      { name: 'Women’s Circle', type: 'private' },
      { name: 'Youth Hangout', type: 'private' },
    ],
    users: [
      { displayName: 'Pastor Luke Harmon', email: 'luke@riverbend.example', bio: 'Dynamic pastor who preaches with warmth and a penchant for memorable one-liners.', traits: ['visionary','pastoral','warm'], attitude: 'Charismatic shepherd' },
      { displayName: 'Sarah Deacon', email: 'sarah@riverbend.example', bio: 'Deacon and organizer of community outreach; known for coordinating soup drives and lullaby playlists.', traits: ['organized','generous','steady'], attitude: 'Practical servant' },
      { displayName: 'Caleb Rivers', email: 'caleb@riverbend.example', bio: 'Youth pastor who brings energy, competitive games, and weekly nacho nights.', traits: ['energetic','mentoring','funny'], attitude: 'High-energy mentor' },
      { displayName: 'Missionary Ana Perez', email: 'ana@riverbend.example', bio: 'Leads missions and travel teams with a suitcase full of adaptable lessons and a heart for local partners.', traits: ['dedicated','adventurous','organized'], attitude: 'Intrepid and focused' },
      { displayName: 'Maggie Fields', email: 'maggie@riverbend.example', bio: 'Worship leader who blends modern praise with acoustic sincerity; will test multiple mic levels.', traits: ['musical','disciplined','creative'], attitude: 'Passionate musician' },
      { displayName: 'Ben Carter', email: 'ben@riverbend.example', bio: 'Children\'s director who builds crafts and faith lessons with equal enthusiasm.', traits: ['playful','patient','nurturing'], attitude: 'Warm and inventive' },
      { displayName: 'Ruth Volunteer', email: 'ruth@riverbend.example', bio: 'Volunteer coordinator with an uncanny memory for schedules and snack preferences.', traits: ['efficient','friendly','organized'], attitude: 'Dependably cheerful' },
      { displayName: 'Tom Hall', email: 'tom@riverbend.example', bio: 'Hospitality lead who runs the coffee hour with the precision of a small café.', traits: ['welcoming','practical','cheerful'], attitude: 'Friendly host' },
      { displayName: 'Young Group Leader', email: 'grouplead@riverbend.example', bio: 'Leads small groups focused on life application and candid conversation.', traits: ['thoughtful','conversational','encouraging'], attitude: 'Inviting and open' },
      { displayName: 'Anna Newcomer', email: 'anna@riverbend.example', bio: 'New member exploring faith traditions and potluck recipes.', traits: ['curious','hopeful','polite'], attitude: 'Gentle and earnest' },
      { displayName: 'Elder Sam', email: 'sam@riverbend.example', bio: 'Retiree volunteer who bakes, mentors, and tells great origin stories.', traits: ['steady','wise','social'], attitude: 'Warmly nostalgic' },
      { displayName: 'Gavin Tech', email: 'gavin@riverbend.example', bio: 'AV and streaming head who secretly judges reverb levels.', traits: ['technical','precise','patient'], attitude: 'Calmly exacting' },
      { displayName: 'Study Host', email: 'study@riverbend.example', bio: 'Bible study host who asks thoughtful questions and brings thermoses.', traits: ['studious','encouraging','kind'], attitude: 'Steady and probing' },
      { displayName: 'Driver Lee', email: 'lee@riverbend.example', bio: 'Outreach driver who knows every backroad and the names of the pets he passes.', traits: ['dependable','friendly','practical'], attitude: 'Solid and friendly' },
      { displayName: 'Youth Volunteer', email: 'youth@riverbend.example', bio: 'Helps at youth events, snack distribution champion.', traits: ['lively','upbeat','helpful'], attitude: 'Eager and bright' },
      { displayName: 'Finance Coordinator', email: 'finance@riverbend.example', bio: 'Manages the books with solemn focus and occasional gentle humor.', traits: ['organized','discreet','exact'], attitude: 'Even-keeled steward' },
      { displayName: 'Prayer Chain Lead', email: 'prayer@riverbend.example', bio: 'Organizes prayer lists and keeps late-night vigil rosters.', traits: ['empathetic','steady','relational'], attitude: 'Compassionate anchor' },
      { displayName: 'Event Planner', email: 'events@riverbend.example', bio: 'Coordinates community rallies and charity drives with a flair for themed decor.', traits: ['resourceful','energetic','detailed'], attitude: 'Creative and tireless' },
      { displayName: 'Nurse on Call', email: 'nurse@riverbend.example', bio: 'Healthcare support at events and a steady presence during crisis.', traits: ['calm','helpful','certified'], attitude: 'Practical caregiver' },
    ],
  },

  {
    name: 'First Covenant Presbyterian',
    slug: 'first-covenant-presbyterian',
    description: 'A methodical and community-minded congregation emphasizing study, fellowship, and mission.',
    logoUrl: avatar('first-covenant-presbyterian'),
    bannerUrl: banner('First Covenant Banner'),
    channels: [
      { name: 'Announcements', type: 'public' },
      { name: 'Session', type: 'private' },
      { name: 'Education', type: 'public' },
      { name: 'Fellowship', type: 'private' },
      { name: 'Missions', type: 'public' },
    ],
    users: [
      { displayName: 'Rev. Alistair McBride', email: 'alistair@firstcovenant.example', bio: 'A contemplative minister who blends scholarly sermons with approachable pastoral care.', traits: ['thoughtful','scholarly','pastoral'], attitude: 'Reflective and steady' },
      { displayName: 'Margaret Clarke (Session Clerk)', email: 'margaret@firstcovenant.example', bio: 'Keeps minutes, motions, and the coffee order in perfect alignment.', traits: ['precise','organised','discreet'], attitude: 'Practical and composed' },
      { displayName: 'Dr. Helena Price', email: 'helena@firstcovenant.example', bio: 'Adult educator who loves probing the intersections of history and faith.', traits: ['studious','kind','patient'], attitude: 'Engaging academic' },
      { displayName: 'Jonathan Morris', email: 'jonathan@firstcovenant.example', bio: 'Leads missions with a detail-oriented approach and a knack for partnership-building.', traits: ['dedicated','pragmatic','warm'], attitude: 'Strategic and kind' },
      { displayName: 'Fellowship Host Nora', email: 'nora@firstcovenant.example', bio: 'Organizer of coffee hours, potlucks, and the occasional panel discussion.', traits: ['inviting','creative','hospitable'], attitude: 'Warm connector' },
      { displayName: 'Music Director Colin', email: 'colin@firstcovenant.example', bio: 'Choir leader who balances hymnody with tasteful modern arrangements.', traits: ['cultured','organized','passionate'], attitude: 'Artful and precise' },
      { displayName: 'Youth Mentor Hannah', email: 'hannah@firstcovenant.example', bio: 'Mentors teens with patience, snacks, and pointed life questions.', traits: ['patient','encouraging','fun'], attitude: 'Affectionate and firm' },
      { displayName: 'Office Manager Celia', email: 'celia@firstcovenant.example', bio: 'Handles admin with quiet efficiency and a friendly welcome at the desk.', traits: ['detailed','efficient','helpful'], attitude: 'Steady and pleasant' },
      { displayName: 'Volunteer Coordinator Sam', email: 'sam@firstcovenant.example', bio: 'Matches skills to needs and keeps rosters tidy.', traits: ['empathetic','systematic','kind'], attitude: 'Methodical and encouraging' },
      { displayName: 'Newcomer Emily', email: 'emily@firstcovenant.example', bio: 'Recently joined and exploring the study groups with bright curiosity.', traits: ['curious','friendly','respectful'], attitude: 'Open and engaged' },
      { displayName: 'Elder Ruth', email: 'ruth@firstcovenant.example', bio: 'Sews altar linens and offers wisdom over tea.', traits: ['steady','social','crafty'], attitude: 'Gentle and wise' },
      { displayName: 'Steward Matthew', email: 'matthew@firstcovenant.example', bio: 'Leads stewardship initiatives and budget conversations with tact.', traits: ['methodical','trustworthy','prudent'], attitude: 'Conscientious and calm' },
      { displayName: 'Facilities Lead Greg', email: 'greg@firstcovenant.example', bio: 'Keeps the building humming and the lights polite.', traits: ['practical','reliable','helpful'], attitude: 'No-nonsense caretaker' },
      { displayName: 'Study Group Leader Naomi', email: 'naomi@firstcovenant.example', bio: 'Hosts weekly theological deep-dives with warm tea and sharper questions.', traits: ['analytic','warm','patient'], attitude: 'Curious facilitator' },
      { displayName: 'Outreach Volunteer Mark', email: 'mark@firstcovenant.example', bio: 'Helps the food pantry and organizes drives with steady hands.', traits: ['giving','caring','humble'], attitude: 'Humble helper' },
      { displayName: 'Tech Support Claire', email: 'claire@firstcovenant.example', bio: 'Runs streaming and AV with silent competence and a soft laugh.', traits: ['precise','calm','technical'], attitude: 'Helpful technician' },
      { displayName: 'Choir Member Beth', email: 'beth@firstcovenant.example', bio: 'Sings alto with steady devotion and tantalizing vibrato.', traits: ['musical','dedicated','friendly'], attitude: 'Joyful and committed' },
      { displayName: 'Parent Rep Olivia', email: 'olivia@firstcovenant.example', bio: 'Liaises with families and coordinates bake-sale sign-ups.', traits: ['communicative','calm','organized'], attitude: 'Organized and empathetic' },
      { displayName: 'Camp Organizer Felix', email: 'felix@firstcovenant.example', bio: 'Retreat planner who knows how to pack a canoe and a conversation.', traits: ['energetic','organized','enthusiastic'], attitude: 'Adventurous and meticulous' },
      { displayName: 'Platform Admin', email: 'admin@firstcovenant.example', bio: 'Local admin and site steward.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },

  {
    name: 'Eldershire Fellowship',
    slug: 'eldershire-fellowship',
    description: 'Mythic-themed reading and roleplay collective focused on quests, book discussions, and craft guilds.',
    logoUrl: avatar('eldershire-fellowship'),
    bannerUrl: banner('Eldershire Fellowship Banner'),
    channels: [
      { name: 'Fellowship Hall', type: 'public' },
      { name: 'Quest Planning', type: 'private' },
      { name: 'Lore Library', type: 'public' },
      { name: 'Craftsmen', type: 'private' },
      { name: 'Moderation', type: 'private' },
    ],
    users: [
      { displayName: 'Lore Master Aldric', email: 'aldric@eldershire.example', bio: 'Keeper of ancestral tales and plot hooks, always ready to spin a new quest thread.', traits: ['wise','patient','erudite'], attitude: 'Grand and mysterious' },
      { displayName: 'Ranger Sylva', email: 'sylva@eldershire.example', bio: 'Guides outdoor meetups and brings thermoses of fortifying broth.', traits: ['hardy','observant','helpful'], attitude: 'Steady and resourceful' },
      { displayName: 'Smith Bren', email: 'bren@eldershire.example', bio: 'Prop-maker extraordinaire who turns scraps into believable relics.', traits: ['craft-focused','precise','friendly'], attitude: 'Practical artisan' },
      { displayName: 'Bard Lio', email: 'lio@eldershire.example', bio: 'Performer and storyteller who remembers everyone\'s heroic deed with a flourish.', traits: ['charismatic','creative','warm'], attitude: 'Flamboyant and kind' },
      { displayName: 'Scout Mira', email: 'mira@eldershire.example', bio: 'Logistics lead with a knack for mapping and keeping lost participants found.', traits: ['organized','adventurous','calm'], attitude: 'Unflappable and cheerful' },
      { displayName: 'Herbalist Nira', email: 'nira@eldershire.example', bio: 'Collects herbs and lore, always with a pocketful of poultices and a soft song.', traits: ['patient','studious','gentle'], attitude: 'Gentle caretaker' },
      { displayName: 'Young Adventurer Theo', email: 'theo@eldershire.example', bio: 'Eager volunteer with a penchant for dramatic entrances and earnest assistance.', traits: ['enthusiastic','brave','clumsy'], attitude: 'Bright and slightly chaotic' },
      { displayName: 'Archivist Lorna', email: 'lorna@eldershire.example', bio: 'Cataloguer of scripts and timelines — your plot never truly dies if Lorna has a note.', traits: ['methodical','tidy','thoughtful'], attitude: 'Meticulous guardian' },
      { displayName: 'Innkeeper Hobb', email: 'hobb@eldershire.example', bio: 'Hosts social nights with wild stew and stranger tales — reservations optional.', traits: ['jovial','welcoming','busy'], attitude: 'Generous and loud' },
      { displayName: 'Mapmaker Ilya', email: 'ilya@eldershire.example', bio: 'Designs feast maps and printed handouts with obsessive compass roses.', traits: ['creative','technical','patient'], attitude: 'Proud cartographer' },
      { displayName: 'Costume Lead Petra', email: 'petra@eldershire.example', bio: 'Seamstress and armor dresser who makes sure hems won\'t betray a heroic tumble.', traits: ['meticulous','tasteful','kind'], attitude: 'Exacting but warm' },
      { displayName: 'Moderator Arne', email: 'arne@eldershire.example', bio: 'Keeps roleplay spaces safe, fun, and open to imaginative mischief.', traits: ['fair','calm','decisive'], attitude: 'Firm and fair' },
      { displayName: 'Archivist Assistant June', email: 'june@eldershire.example', bio: 'Helps Lorna with indexing and tea-making.', traits: ['helpful','studious','thorough'], attitude: 'Steady and bright' },
      { displayName: 'Newcomer Cass', email: 'cass@eldershire.example', bio: 'First-time attendee eager to learn sword etiquette and storytelling cues.', traits: ['wide-eyed','polite','open'], attitude: 'Excited apprentice' },
      { displayName: 'Storyteller Rian', email: 'rian@eldershire.example', bio: 'Writes scene scripts and throws in a twist where you least expect it.', traits: ['imaginative','playful','focused'], attitude: 'Clever and theatrical' },
      { displayName: 'Photographer Dax', email: 'dax@eldershire.example', bio: 'Captures the pageantry and the quiet smiles between battles.', traits: ['observant','patient','creative'], attitude: 'Soft-eyed documentarian' },
      { displayName: 'Weekend Volunteer Mae', email: 'mae@eldershire.example', bio: 'Turns up every weekend with rope, glue, and moral support.', traits: ['reliable','cheerful','practical'], attitude: 'Dependable hands' },
      { displayName: 'Scholar Brenna', email: 'brenna@eldershire.example', bio: 'Researches background histories and proposes plausible ancestral quarrels.', traits: ['studious','reserved','precise'], attitude: 'Thoughtful and exact' },
      { displayName: 'Food Steward Omar', email: 'omar@eldershire.example', bio: 'Organizes feasts with a love for spice and communal plates.', traits: ['practical','culinary','warm'], attitude: 'Generous chef' },
      { displayName: 'Platform Admin', email: 'admin@eldershire.example', bio: 'Platform admin for the mythic collective.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },

  {
    name: 'Tam Bao Meditation Center (Baton Rouge)',
    slug: 'tam-bao-br',
    description: 'A meditation and mindfulness center offering guided sits, dharma talks, and retreats.',
    logoUrl: avatar('tam-bao-br'),
    bannerUrl: banner('Tam Bao Meditation Center Banner'),
    channels: [
      { name: 'Announcements', type: 'public' },
      { name: 'Meditation Schedules', type: 'public' },
      { name: 'Teachers', type: 'private' },
      { name: 'Sangha Chat', type: 'private' },
      { name: 'Retreats', type: 'public' },
    ],
    users: [
      { displayName: 'Venerable Thich An', email: 'thich@tambao.example', bio: 'Respected teacher who offers gentle guidance and practical instruction for daily practice.', traits: ['calm','wise','patient'], attitude: 'Serene mentor' },
      { displayName: 'Brother Minh Tran', email: 'minh@tambao.example', bio: 'Practice coordinator who shepherds sits and keeps the kettle warm.', traits: ['steady','punctual','kind'], attitude: 'Supportive coordinator' },
      { displayName: 'Sister Hoa Le', email: 'hoa@tambao.example', bio: 'Leads dharma talks with clarity and warmth, known for literal and metaphorical potlucks.', traits: ['insightful','articulate','warm'], attitude: 'Engaging teacher' },
      { displayName: 'Retreat Lead Priya', email: 'priya@tambao.example', bio: 'Organizes retreats with meticulous detail and a calming playlist.', traits: ['organized','thoughtful','calm'], attitude: 'Practical and mindful' },
      { displayName: 'Volunteer Coordinator Sam', email: 'sam@tambao.example', bio: 'Coordinates volunteers and keeps the schedule humming.', traits: ['humble','hardworking','gentle'], attitude: 'Steady helper' },
      { displayName: 'Anna Community', email: 'anna@tambao.example', bio: 'Regular attendee who brings thoughtful questions and tea cookies.', traits: ['quiet','gentle','curious'], attitude: 'Quietly curious' },
      { displayName: 'Newcomer Daniel', email: 'daniel@tambao.example', bio: 'Exploring meditation for the first time with polite concentration.', traits: ['tentative','open','kind'], attitude: 'Open and earnest' },
      { displayName: 'Instructor Mei', email: 'mei@tambao.example', bio: 'Experienced teacher with approachable instruction for beginners.', traits: ['patient','clear','reassuring'], attitude: 'Warmly instructive' },
      { displayName: 'Youth Lead Omar', email: 'omar@tambao.example', bio: 'Engages youth with playful practices and mindful games.', traits: ['warm','playful','patient'], attitude: 'Fun and thoughtful' },
      { displayName: 'Tea Host Li', email: 'li@tambao.example', bio: 'Hospitality lead who sets a calm welcome table and great biscuits.', traits: ['hospitable','calm','cheerful'], attitude: 'Generous host' },
      { displayName: 'Translator Fatima', email: 'fatima@tambao.example', bio: 'Multilingual bridge who helps newcomers feel included.', traits: ['linguist','patient','precise'], attitude: 'Kind mediator' },
      { displayName: 'Archivist Noor', email: 'noor@tambao.example', bio: 'Records talks and keeps a tidy archive for future students.', traits: ['methodical','attentive','steady'], attitude: 'Meticulous and calm' },
      { displayName: 'Grounds Steward Kofi', email: 'kofi@tambao.example', bio: 'Keeps the grounds serene and the pathways swept.', traits: ['quiet','reliable','considerate'], attitude: 'Steady caretaker' },
      { displayName: 'Yoga Liaison Priyanka', email: 'priyanka@tambao.example', bio: 'Cross-discipline facilitator who gently introduces somatic practices.', traits: ['flexible','gentle','encouraging'], attitude: 'Softly energetic' },
      { displayName: 'Fundraising Liaison Maya', email: 'maya@tambao.example', bio: 'Keeps community support flowing with grace and tact.', traits: ['diplomatic','organized','thoughtful'], attitude: 'Persuasive and kind' },
      { displayName: 'Workshop Host Arun', email: 'arun@tambao.example', bio: 'Leads workshops with clear structure and warm humor.', traits: ['prepared','methodical','warm'], attitude: 'Energetic and steady' },
      { displayName: 'Elder Practitioner Sora', email: 'sora@tambao.example', bio: 'Mentor figure who patiently guides newer practitioners.', traits: ['serene','patient','wise'], attitude: 'Gentle sage' },
      { displayName: 'Tech Support Ken', email: 'ken@tambao.example', bio: 'Streams talks and keeps the mics honest.', traits: ['technical','quiet','dependable'], attitude: 'Unobtrusive and helpful' },
      { displayName: 'Platform Admin', email: 'admin@tambao.example', bio: 'Platform admin for the meditation community.', traits: ['authoritative','helpful','omniscient'], attitude: 'Steady support' },
    ],
  },

  {
    name: 'Al-Noor Community Mosque',
    slug: 'al-noor-mosque',
    description: 'Community mosque offering prayers, study circles, outreach, and community events.',
    logoUrl: avatar('al-noor-mosque'),
    bannerUrl: banner('Al-Noor Community Mosque Banner'),
    channels: [
      { name: 'Masjid Announcements', type: 'public' },
      { name: 'Quran Study', type: 'private' },
      { name: 'Youth Circle', type: 'private' },
      { name: 'Charity Ops', type: 'public' },
      { name: 'Imams & Staff', type: 'private' },
    ],
    users: [
      { displayName: 'Imam Ahmed Al-Hassan', email: 'ahmed@al-noor.example', bio: 'Learned and gracious imam who balances sermon depth with approachable community advice.', traits: ['learned','calm','pastoral'], attitude: 'Warmly instructive' },
      { displayName: 'Afif Al-Masri', email: 'afif@al-noor.example', bio: 'Youth coordinator known for organizing vibrant Ramadan iftars and soccer nights; quick with a joke and a dates plate.', traits: ['energetic','relatable','community-minded'], attitude: 'Energetic connector' },
      { displayName: 'Aisha Rahman', email: 'aisha@al-noor.example', bio: 'Dawah and outreach organizer who runs classes on faith, history, and community engagement.', traits: ['warm','articulate','outreach-minded'], attitude: 'Inviting educator' },
      { displayName: 'Ustadh Yusuf', email: 'yusuf@al-noor.example', bio: 'Quran teacher whose recitation is precise and whose patience is endless.', traits: ['patient','disciplined','clear'], attitude: 'Calm mentor' },
      { displayName: 'Nadia Saleh', email: 'nadia@al-noor.example', bio: 'Leads the women\'s circle with compassionate organization and a stash of tea.', traits: ['compassionate','organized','discreet'], attitude: 'Kind and discreet' },
      { displayName: 'Fatima Noor', email: 'fatima@al-noor.example', bio: 'Education admin who coordinates classes, volunteers, and the neighborhood support roster.', traits: ['organized','friendly','efficient'], attitude: 'Helpful organizer' },
      { displayName: 'Omar Haddad', email: 'omar@al-noor.example', bio: 'Facility steward who keeps the mosque clean, welcoming, and ready for guests.', traits: ['practical','tidy','helpful'], attitude: 'Steady caretaker' },
      { displayName: 'Khadija Rahimi', email: 'khadija@al-noor.example', bio: 'Halal coordinator and food lead — ensures every plate is served with care and rules observed.', traits: ['detail-oriented','practical','helpful'], attitude: 'Meticulous and kind' },
      { displayName: 'Bilal Hassan', email: 'bilal@al-noor.example', bio: 'Volunteer who mans the Ramadan kitchen and knows every auntie\'s favorite spice.', traits: ['hardworking','kind','practical'], attitude: 'Generous and committed' },
      { displayName: 'Layla Qureshi', email: 'layla@al-noor.example', bio: 'Community nurse who organizes health drives and discreet support for families in need.', traits: ['caring','practical','reliable'], attitude: 'Compassionate organizer' },
      { displayName: 'Samir Khan', email: 'samir@al-noor.example', bio: 'Outreach volunteer who builds school partnerships and welcomes newcomers with a tidy smile.', traits: ['kind','patient','resilient'], attitude: 'Humble connector' },
      { displayName: 'Heba Aziz', email: 'heba@al-noor.example', bio: 'Translator and multilingual bridge for newcomers and elders.', traits: ['multilingual','patient','helpful'], attitude: 'Calm mediator' },
      { displayName: 'Security Lead Tariq', email: 'tariq@al-noor.example', bio: 'Keeps the venue safe with calm vigilance and a neighborly nod.', traits: ['responsible','calm','observant'], attitude: 'Protective and steady' },
      { displayName: 'Newcomer Yusuf', email: 'new@al-noor.example', bio: 'Recently joined and exploring prayer routines and community gatherings.', traits: ['curious','tentative','polite'], attitude: 'Quietly eager' },
      { displayName: 'Platform Admin', email: 'admin@al-noor.example', bio: 'Platform administrator for community operations.', traits: ['authoritative','helpful','omniscient'], attitude: 'Helpful steward' },
    ],
  },

  {
    name: 'Sri Lakshmi Cultural Temple',
    slug: 'sri-lakshmi-temple',
    description: 'Temple community focusing on puja schedules, cultural classes, and community festivals.',
    logoUrl: avatar('sri-lakshmi-temple'),
    bannerUrl: banner('Sri Lakshmi Temple Banner'),
    channels: [
      { name: 'Temple Announcements', type: 'public' },
      { name: 'Priests', type: 'private' },
      { name: 'Cultural Events', type: 'public' },
      { name: 'Youth Circle', type: 'private' },
      { name: 'Volunteers', type: 'private' },
    ],
    users: [
      { displayName: 'Pujari Ramesh Iyer', email: 'ramesh@srilakshmi.example', bio: 'Head priest who leads rituals with deep care and a steady hand.', traits: ['learned','calm','ceremonial'], attitude: 'Reverent and welcoming' },
      { displayName: 'Anjali Rao', email: 'anjali@srilakshmi.example', bio: 'Director of cultural events who choreographs festivals with colors and precision.', traits: ['creative','organized','energetic'], attitude: 'Vibrant coordinator' },
      { displayName: 'Priya Menon', email: 'priya@srilakshmi.example', bio: 'Youth coordinator who teaches bhajans and story sessions with gentle humor.', traits: ['playful','patient','caring'], attitude: 'Warm mentor' },
      { displayName: 'Suresh Patel', email: 'suresh@srilakshmi.example', bio: 'Facility steward who ensures puja items are polished and puja schedules tidy.', traits: ['practical','attentive','tidy'], attitude: 'Reliable caretaker' },
      { displayName: 'Radha Kumari', email: 'radha@srilakshmi.example', bio: 'Bhajan leader with a voice like incense — brings warmth to every evening.', traits: ['musical','patient','warm'], attitude: 'Melodic and kind' },
      { displayName: 'Lalita Sharma', email: 'lalita@srilakshmi.example', bio: 'Dance instructor who teaches classical moves and community confidence.', traits: ['artistic','disciplined','encouraging'], attitude: 'Graceful teacher' },
      { displayName: 'Kumar Das', email: 'kumar@srilakshmi.example', bio: 'Leads charity drives and coordinates prasad distribution with a smile.', traits: ['generous','pragmatic','organized'], attitude: 'Generous organizer' },
      { displayName: 'Meena Volunteer', email: 'meena@srilakshmi.example', bio: 'Prepares prasad and decor with tireless cheer.', traits: ['cheerful','hardworking','kind'], attitude: 'Cheerful helper' },
      { displayName: 'Shruti the Archivist', email: 'shruti@srilakshmi.example', bio: 'Keeps temple texts and program archives neatly indexed.', traits: ['studious','careful','patient'], attitude: 'Quietly meticulous' },
      { displayName: 'Language Teacher Arjun', email: 'arjun@srilakshmi.example', bio: 'Teaches scriptural languages and the gentle cadences of chant.', traits: ['patient','educated','calm'], attitude: 'Gentle educator' },
      { displayName: 'Elder Vijay', email: 'vijay@srilakshmi.example', bio: 'Longtime devotee who remembers rites and recipes from decades past.', traits: ['steady','reverent','social'], attitude: 'Fond and steady' },
      { displayName: 'Fundraiser Priyanka', email: 'funds@srilakshmi.example', bio: 'Keeps festival fundraising flowing and plates full.', traits: ['diplomatic','trustworthy','kind'], attitude: 'Friendly strategist' },
      { displayName: 'New Attendee Kavya', email: 'kavya@srilakshmi.example', bio: 'Curious newcomer exploring puja rituals and floral offerings.', traits: ['curious','respectful','tentative'], attitude: 'Respectful and bright' },
      { displayName: 'Craft Lead Rekha', email: 'rekha@srilakshmi.example', bio: 'Leads rangoli and decor with bright colors and steady hands.', traits: ['artistic','precise','patient'], attitude: 'Deliberate creator' },
      { displayName: 'Tech Support Arav', email: 'arav@srilakshmi.example', bio: 'Streams services and keeps mics clear so chants travel cleanly.', traits: ['practical','technical','discreet'], attitude: 'Calm technician' },
      { displayName: 'Youth Mentor Meera', email: 'meera@srilakshmi.example', bio: 'Guides teens with stories, craft, and festival history.', traits: ['patient','encouraging','stable'], attitude: 'Warm guide' },
      { displayName: 'Community Liaison Nirmal', email: 'nirmal@srilakshmi.example', bio: 'Builds partnerships with local cultural groups and schools.', traits: ['communicative','diplomatic','warm'], attitude: 'Connector and diplomat' },
      { displayName: 'Platform Admin', email: 'admin@srilakshmi.example', bio: 'Platform admin for the temple community.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },

  {
    name: 'Reason & Exchange Collective',
    slug: 'reason-exchange',
    description: 'Secular community prioritizing discussion, civic engagement, book groups, and science outreach.',
    logoUrl: avatar('reason-exchange'),
    bannerUrl: banner('Reason & Exchange Banner'),
    channels: [
      { name: 'Announcements', type: 'public' },
      { name: 'Debates', type: 'public' },
      { name: 'Organizers', type: 'private' },
      { name: 'Workshops', type: 'public' },
      { name: 'Social', type: 'public' },
    ],
    users: [
      { displayName: 'Dr. Elena Royce', email: 'elena@reason.example', bio: 'Organizer and public intellectual who loves panels, clarity, and a well-timed coffee.', traits: ['analytical','open-minded','practical'], attitude: 'Cerebral and engaging' },
      { displayName: 'Marcus Lee (Moderator)', email: 'marcus@reason.example', bio: 'Keeps debates civil and ensures evidence gets equal stage time.', traits: ['calm','neutral','fair'], attitude: 'Measured and fair' },
      { displayName: 'Samira Khan', email: 'samira@reason.example', bio: 'Leads science outreach and designs kid-friendly experiments that somehow always involve smoke.', traits: ['curious','methodical','communicative'], attitude: 'Playful scientist' },
      { displayName: 'Prof. Jonah Adler', email: 'jonah@reason.example', bio: 'Ethics scholar who loves thought experiments and slow, polite arguments.', traits: ['thoughtful','principled','patient'], attitude: 'Wry academic' },
      { displayName: 'Volunteer Coordinator Tess', email: 'tess@reason.example', bio: 'Organizes service projects and remembers everyone\'s t-shirt size.', traits: ['efficient','friendly','organized'], attitude: 'Personable organizer' },
      { displayName: 'Newcomer Omar', email: 'omar@reason.example', bio: 'Curious about civic processes and eager to attend a debate.', traits: ['curious','polite','tentative'], attitude: 'Engaged newcomer' },
      { displayName: 'Civic Liaison Priyanka', email: 'priyanka@reason.example', bio: 'Runs town-halls with a focus on listening and follow-up.', traits: ['sociable','diplomatic','organized'], attitude: 'Calm connector' },
      { displayName: 'Book Club Host Mara', email: 'mara@reason.example', bio: 'Organizes monthly reads with thematic snacks and strong opinions.', traits: ['literary','warm','thoughtful'], attitude: 'Inviting and opinionated' },
      { displayName: 'Data Analyst Ken', email: 'ken@reason.example', bio: 'Tracks engagement metrics and loves a neat CSV.', traits: ['precise','nerdy','helpful'], attitude: 'Quietly brilliant' },
      { displayName: 'Event Host Lina', email: 'lina@reason.example', bio: 'Schedules workshops with impeccable timing and a playlist to match.', traits: ['organized','cheerful','practical'], attitude: 'Efficient and fun' },
      { displayName: 'Volunteer Jay', email: 'jay@reason.example', bio: 'Helps at events and quietly rearranges chairs for maximum social flow.', traits: ['giving','hardworking','low-key'], attitude: 'Steady helper' },
      { displayName: 'Podcast Host Noor', email: 'noor@reason.example', bio: 'Produces community interviews with curiosity and sharp edits.', traits: ['creative','persuasive','resourceful'], attitude: 'Curious storyteller' },
      { displayName: 'Educator Miguel', email: 'miguel@reason.example', bio: 'Runs workshops on civic tech and public reasoning.', traits: ['patient','didactic','engaging'], attitude: 'Patient teacher' },
      { displayName: 'Moderator Alex', email: 'alex@reason.example', bio: 'Maintains community standards with a calm tone and a firm hand.', traits: ['fair','decisive','calm'], attitude: 'Balanced moderator' },
      { displayName: 'Researcher Priya', email: 'priya@reason.example', bio: 'Publishes community resources and whitepapers with immaculate footnotes.', traits: ['studious','precise','quiet'], attitude: 'Diligent and exact' },
      { displayName: 'Tech Lead Sam', email: 'tech@reason.example', bio: 'Keeps the platform and workshop tools humming.', traits: ['technical','measured','pragmatic'], attitude: 'Methodical fixer' },
      { displayName: 'Community Host Ben', email: 'community@reason.example', bio: 'Organizes socials to keep the conversation from going stale.', traits: ['gregarious','warm','welcoming'], attitude: 'Friendly connector' },
      { displayName: 'Student Liaison Zoe', email: 'zoe@reason.example', bio: 'Represents students and brings lively questions to panels.', traits: ['inquisitive','earnest','busy'], attitude: 'Eager and bright' },
      { displayName: 'Platform Admin', email: 'admin@reason.example', bio: 'Platform administrator for the secular collective.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },

  {
    name: 'Pedal Forward Foundation',
    slug: 'pedal-forward',
    description: 'Nonprofit training kids to repair bicycles, building skills, confidence, and community.',
    logoUrl: avatar('pedal-forward'),
    bannerUrl: banner('Pedal Forward Banner'),
    channels: [
      { name: 'Workshop Announcements', type: 'public' },
      { name: 'Volunteer Team', type: 'private' },
      { name: 'Donors', type: 'private' },
      { name: 'Youth Programs', type: 'public' },
      { name: 'Equipment Swap', type: 'public' },
    ],
    users: [
      { displayName: 'Afternoon Ed (Executive Director)', email: 'ed@pedalforward.example', bio: 'Visionary founder who rides a battered commuter bike and dreams of a city where every child pedals with pride.', traits: ['visionary','pragmatic','friendly'], attitude: 'Optimistic leader' },
      { displayName: 'Maya Santos', email: 'maya@pedalforward.example', bio: 'Workshop lead who teaches kids to grease chains and the art of fixing a flat tire with a grin.', traits: ['patient','skilled','encouraging'], attitude: 'Playful instructor' },
      { displayName: 'Carlos Vega', email: 'carlos@pedalforward.example', bio: 'Volunteer coordinator who knows every volunteer\'s coffee order.', traits: ['organized','kind','prompt'], attitude: 'Practical and warm' },
      { displayName: 'Tyrell Mechanics', email: 'tyrell@pedalforward.example', bio: 'Senior mechanic with a knack for explaining torque using metaphors about life.', traits: ['skilled','patient','hands-on'], attitude: 'Gentle craftsman' },
      { displayName: 'Jamal Mentor', email: 'jamal@pedalforward.example', bio: 'Youth mentor who builds skills and confidence in equal measure.', traits: ['warm','firm','instructive'], attitude: 'Empowering and patient' },
      { displayName: 'Grace Donor', email: 'grace@pedalforward.example', bio: 'Runs donor relations with gratitude letters and personalized tire pumps.', traits: ['diplomatic','grateful','organized'], attitude: 'Gracious and strategic' },
      { displayName: 'Logistics Nina', email: 'nina@pedalforward.example', bio: 'Keeps parts, lists, and volunteers in tidy order — the quiet force of every event.', traits: ['systematic','pragmatic','helpful'], attitude: 'Calmly efficient' },
      { displayName: 'Fundraiser Liam', email: 'liam@pedalforward.example', bio: 'Plans events, pitches grants, and knows a good story when he hears one.', traits: ['persuasive','strategic','energetic'], attitude: 'Ambitious and personable' },
      { displayName: 'School Liaison Priya', email: 'priya@pedalforward.example', bio: 'Builds school partnerships and arranges field trips with precision.', traits: ['communicative','reliable','kind'], attitude: 'Friendly coordinator' },
      { displayName: 'Rafael (Kid Participant)', email: 'rafael@pedalforward.example', bio: 'Learner who loves changing gears and showing off his first solo ride.', traits: ['eager','hands-on','shy'], attitude: 'Proud and bright' },
      { displayName: 'Zoe (Kid Participant)', email: 'zoe@pedalforward.example', bio: 'Brave kid who prefers blue helmets and fast turns.', traits: ['brave','curious','energetic'], attitude: 'Bold and cheerful' },
      { displayName: 'Grandma June', email: 'june@pedalforward.example', bio: 'Regular volunteer with a knack for mending seats and hearts alike.', traits: ['steady','patient','skilled'], attitude: 'Warmly experienced' },
      { displayName: 'Media Lead Omar', email: 'media@pedalforward.example', bio: 'Documents workshops and finds the perfect before/after shot.', traits: ['creative','proactive','friendly'], attitude: 'Energetic storyteller' },
      { displayName: 'Safety Officer Nia', email: 'nia@pedalforward.example', bio: 'Ensures safe practices and pretty reflective vests.', traits: ['careful','stern','reliable'], attitude: 'Vigilant and kind' },
      { displayName: 'Outreach Liaison Rosa', email: 'rosa@pedalforward.example', bio: 'Connects families with programs and remembers names.', traits: ['outgoing','caring','resourceful'], attitude: 'Warm connector' },
      { displayName: 'Parts Manager Ben', email: 'parts@pedalforward.example', bio: 'Carefully catalogs patches, spokes, and small miracles.', traits: ['methodical','efficient','helpful'], attitude: 'Organized and patient' },
      { displayName: 'Teen Volunteer Kai', email: 'kai@pedalforward.example', bio: 'Helps peers fix bikes and earn summer hours.', traits: ['eager','helpful','patient'], attitude: 'Enthusiastic helper' },
      { displayName: 'Photographer Leo', email: 'photo@pedalforward.example', bio: 'Documents the small triumphs of every ride.', traits: ['observant','creative','friendly'], attitude: 'Humble storyteller' },
      { displayName: 'Admin Assistant', email: 'adminasst@pedalforward.example', bio: 'Handles paperwork and keeps everything moving.', traits: ['efficient','polite','helpful'], attitude: 'Quietly indispensable' },
    ],
  },

  {
    name: 'Corner Friends Club',
    slug: 'corner-friends-club',
    description: 'Casual social platform for a friend group to share events, memes, and private messages.',
    logoUrl: avatar('corner-friends-club'),
    bannerUrl: banner('Corner Friends Club Banner'),
    channels: [
      { name: 'Watercooler', type: 'public' },
      { name: 'Memes & Pics', type: 'public' },
      { name: 'Weekend Plans', type: 'private' },
      { name: 'Foodies', type: 'private' },
      { name: 'Moderators', type: 'private' },
    ],
    users: [
      { displayName: 'Jenna Bright', email: 'jenna@cornerfriends.example', bio: 'Organizer of brunches and lover of too-many-mimosas; keeps the group calendar like a sacred text.', traits: ['outgoing','funny','warm'], attitude: 'Energetic planner' },
      { displayName: 'Marcus "Buckets"', email: 'marcus@cornerfriends.example', bio: 'Sports fanatic with spirited takes and a big-hearted shout for every play.', traits: ['playful','loyal','loud'], attitude: 'Boisterous fan' },
      { displayName: 'Priya Nair', email: 'priya@cornerfriends.example', bio: 'Foodie and photographer who judges dishes gently and captures them beautifully.', traits: ['creative','precise','friendly'], attitude: 'Tasteful and kind' },
      { displayName: 'Alex Chen', email: 'alex@cornerfriends.example', bio: 'Tech-savvy problem-solver who brings chargers and sarcasm in equal measure.', traits: ['nerdy','helpful','wry'], attitude: 'Dryly helpful' },
      { displayName: 'Samira "Sam" Park', email: 'sam@cornerfriends.example', bio: 'Dog-owner extraordinaire who organizes walks and melt-in-your-mouth treats.', traits: ['caring','playful','dependable'], attitude: 'Warm and steady' },
      { displayName: 'Zoe Armitage', email: 'zoe@cornerfriends.example', bio: 'Artist who turns brunch napkins into masterpieces and deep conversation into collage.', traits: ['imaginative','moody','kind'], attitude: 'Moody creative' },
      { displayName: 'Nate Rivers', email: 'nate@cornerfriends.example', bio: 'Music lover who curates playlists that pretend to be edgy but are deeply comforting.', traits: ['laid-back','genial','witty'], attitude: 'Chill curator' },
      { displayName: 'Lia Gomez', email: 'lia@cornerfriends.example', bio: 'Fitness buddy who leads impromptu runs and cheers louder than you deserve.', traits: ['driven','cheerful','encouraging'], attitude: 'Encouraging motivator' },
      { displayName: 'Owen Meme-Lord', email: 'owen@cornerfriends.example', bio: 'Curates the group\'s meme diet with alarming taste and timing.', traits: ['irreverent','clever','social'], attitude: 'Irreverent entertainer' },
      { displayName: 'Tanya Celebrates', email: 'tanya@cornerfriends.example', bio: 'Party planner who makes sure every birthday has a theme and a playlist.', traits: ['thoughtful','hospitable','meticulous'], attitude: 'Organized host' },
      { displayName: 'New Joiner Casey', email: 'new@cornerfriends.example', bio: 'New to the crew and excited about brunches and group chats.', traits: ['nervous','excited','polite'], attitude: 'Brightly curious' },
      { displayName: 'Photo Lead Arun', email: 'photo@cornerfriends.example', bio: 'Captures candid moments and the occasional photobomb.', traits: ['observant','creative','friendly'], attitude: 'Eye for moments' },
      { displayName: 'Planner Zoe', email: 'planner@cornerfriends.example', bio: 'Schedules meetups so people show up and snacks arrive.', traits: ['organized','punctual','kind'], attitude: 'Practical and kind' },
      { displayName: 'Grillmaster Ben', email: 'bbq@cornerfriends.example', bio: 'Barbecue master with secret rub and louder laugh.', traits: ['jovial','practical','tasty'], attitude: 'Gregarious and skilled' },
      { displayName: 'Gamer Chloe', email: 'gamer@cornerfriends.example', bio: 'Hosts game nights and keeps the leaderboard free of cheaters.', traits: ['competitive','witty','loyal'], attitude: 'Playful competitor' },
      { displayName: 'Baker June', email: 'baker@cornerfriends.example', bio: 'Brings desserts that double as emotional support.', traits: ['sweet','precise','cheerful'], attitude: 'Gentle and sugary' },
      { displayName: 'Volunteer Maya', email: 'vol@cornerfriends.example', bio: 'Organizes charity efforts and community giving days.', traits: ['giving','proactive','fun'], attitude: 'Generous organizer' },
      { displayName: 'Student Theo', email: 'student@cornerfriends.example', bio: 'Busy student who drops by for group energy and moral support.', traits: ['juggling','eager','polite'], attitude: 'Polite and busy' },
      { displayName: 'Parent Rep Nicole', email: 'parent@cornerfriends.example', bio: 'Manages playdates and snack schedules with authoritative grace.', traits: ['patient','organized','kind'], attitude: 'Practical caregiver' },
      { displayName: 'Platform Admin', email: 'admin@cornerfriends.example', bio: 'Platform admin and chat moderator.', traits: ['authoritative','helpful','omniscient'], attitude: 'Helpful steward' },
    ],
  },

  {
    name: 'Foundry Makerspace Collective',
    slug: 'foundry-makerspace',
    description: 'Community makerspace where members collaborate on fabrication, electronics, woodworking, and teach classes.',
    logoUrl: avatar('foundry-makerspace'),
    bannerUrl: banner('Foundry Makerspace Banner'),
    channels: [
      { name: 'Announcements', type: 'public' },
      { name: 'Tool Safety', type: 'public' },
      { name: 'CNC Users', type: 'private' },
      { name: 'Electronics Bench', type: 'private' },
      { name: 'Events & Classes', type: 'public' },
    ],
    users: [
      { displayName: 'Riley Forge', email: 'riley@foundry.example', bio: 'Shop manager who knows every tool by name and remembers everyone\'s first project.', traits: ['knowledgeable','safety-focused','genial'], attitude: 'Practical mentor' },
      { displayName: 'Hannah Wood', email: 'hannah@foundry.example', bio: 'Woodworking lead who can coax beauty from a rough plank and teach safe joinery with a smile.', traits: ['skilled','patient','creative'], attitude: 'Patient craftsman' },
      { displayName: 'Raj Patel', email: 'raj@foundry.example', bio: 'Electronics mentor whose bench is a maze of LEDs and helpful diagrams.', traits: ['technical','careful','encouraging'], attitude: 'Enthusiastic teacher' },
      { displayName: 'Marta CNC', email: 'marta@foundry.example', bio: 'CNC specialist who treats G-code like poetry and runs machines like clockwork.', traits: ['meticulous','safety-first','calm'], attitude: 'Methodical and calm' },
      { displayName: 'Eli Student', email: 'eli@foundry.example', bio: 'Fabrication student, always with a pencil behind the ear and a new idea to try.', traits: ['curious','clumsy','enthusiastic'], attitude: 'Eager learner' },
      { displayName: 'Sam Volunteer', email: 'sam@foundry.example', bio: 'Workshop assistant who preps materials and offers reliable hands on busy nights.', traits: ['steady','helpful','friendly'], attitude: 'Dependable helper' },
      { displayName: 'Priya Events', email: 'priya@foundry.example', bio: 'Event coordinator who schedules demos and keeps the snack table heroic.', traits: ['organised','social','efficient'], attitude: 'Organized and warm' },
      { displayName: 'Jordan Safety', email: 'jordan@foundry.example', bio: 'Safety officer who insists on goggles but tells great workshop stories afterward.', traits: ['firm','attentive','helpful'], attitude: 'Strict but kind' },
      { displayName: 'Claire Design', email: 'claire@foundry.example', bio: 'CAD designer who translates messy sketches into printable triumphs.', traits: ['creative','technical','patient'], attitude: 'Curious problem-solver' },
      { displayName: 'Omar Photo', email: 'omar@foundry.example', bio: 'Photographer capturing the sparks, sawdust, and proud grins.', traits: ['observant','creative','friendly'], attitude: 'Documentarian with a smile' },
      { displayName: 'Fiona Materials', email: 'fiona@foundry.example', bio: 'Materials manager who knows where every bolt and filament lives.', traits: ['methodical','efficient','helpful'], attitude: 'Organized anchor' },
      { displayName: 'Diego Liaison', email: 'diego@foundry.example', bio: 'Community liaison who brings in partnerships and curious guests.', traits: ['diplomatic','engaging','friendly'], attitude: 'Connector and promoter' },
      { displayName: 'Noah Apprentice', email: 'noah@foundry.example', bio: 'Teen apprentice learning trade skills and how to respect a bandsaw.', traits: ['eager','respectful','growing'], attitude: 'Bright and earnest' },
      { displayName: 'Professor Bell', email: 'bell@foundry.example', bio: 'Instructor and longtime maker who breaks down complex processes into clear steps.', traits: ['experienced','patient','articulate'], attitude: 'Gentle expert' },
      { displayName: 'Ivy Admin', email: 'ivy@foundry.example', bio: 'Administrative lead who keeps memberships and schedules in happy order.', traits: ['supervising','supportive','helpful'], attitude: 'Organized and calm' },
      { displayName: 'Maya Startup', email: 'maya@foundry.example', bio: 'Founder tinkering on the next prototype and running on cold brew and optimism.', traits: ['driven','focused','resourceful'], attitude: 'Ambitious builder' },
      { displayName: 'Alex Designer', email: 'alex@foundry.example', bio: 'Volunteer designer helping projects find shape and color.', traits: ['creative','collaborative','friendly'], attitude: 'Helpful collaborator' },
      { displayName: 'June Host', email: 'june@foundry.example', bio: 'Event host who welcomes guests like old friends and runs demos with flair.', traits: ['sociable','warm','organized'], attitude: 'Charismatic host' },
      { displayName: 'Joe Repair', email: 'joe@foundry.example', bio: 'Repair cafe lead — he can fix a lamp and tell you the most useful history about it.', traits: ['practical','generous','patient'], attitude: 'Skilled and funny' },
      { displayName: 'New Member', email: 'new@foundry.example', bio: 'New joiner trying tools, asking many good questions, and learning fast.', traits: ['curious','tentative','polite'], attitude: 'Excited beginner' },
    ],
  },

  {
    name: 'Open Source Guild',
    slug: 'opensource-guild',
    description: 'Community hub for OSS contributors: project rooms, mentorship, code clinics, and release planning.',
    logoUrl: avatar('opensource-guild'),
    bannerUrl: banner('Open Source Guild Banner'),
    channels: [
      { name: 'Release Announcements', type: 'public' },
      { name: 'Maintainers', type: 'private' },
      { name: 'Mentorship', type: 'private' },
      { name: 'Help Desk', type: 'public' },
      { name: 'Social', type: 'public' },
    ],
    users: [
      { displayName: 'Casey Maintainer', email: 'casey@ossguild.example', bio: 'Project lead who shepherds releases with calm and an eye for contributors.', traits: ['focused','pragmatic','communicative'], attitude: 'Patient steward' },
      { displayName: 'Mina Contributor', email: 'mina@ossguild.example', bio: 'Regular contributor who replies to issues at 2am and brings helpful PRs.', traits: ['curious','diligent','team-oriented'], attitude: 'Steady coder' },
      { displayName: 'Eve Mentor', email: 'eve@ossguild.example', bio: 'Guides juniors with practical code reviews and good coffee advice.', traits: ['patient','experienced','kind'], attitude: 'Gentle teacher' },
      { displayName: 'Ken Newbie', email: 'ken@ossguild.example', bio: 'First-time contributor, eager and a little nervous; asks great questions.', traits: ['eager','nervous','open'], attitude: 'Enthusiastic learner' },
      { displayName: 'Zoe Release', email: 'zoe@ossguild.example', bio: 'Coordinates releases like a conductor and keeps the changelog tidy.', traits: ['organized','calm','precise'], attitude: 'Composed orchestrator' },
      { displayName: 'Priya Docs', email: 'priya@ossguild.example', bio: 'Documentation lead who makes complicated APIs readable and even charming.', traits: ['meticulous','clear','patient'], attitude: 'Clarity-first writer' },
      { displayName: 'Aaron QA', email: 'aaron@ossguild.example', bio: 'QA lead who knows edge cases and hates flaky tests more than bugs.', traits: ['detail-oriented','methodical','fair'], attitude: 'Staunch tester' },
      { displayName: 'Sam Designer', email: 'sam@ossguild.example', bio: 'UX thinker who balances polish with accessibility.', traits: ['creative','pragmatic','collaborative'], attitude: 'Considered artist' },
      { displayName: 'Riley Mod', email: 'riley@ossguild.example', bio: 'Moderator who keeps chats friendly and issues actionable.', traits: ['fair','calm','impartial'], attitude: 'Even-handed steward' },
      { displayName: 'Nora Security', email: 'nora@ossguild.example', bio: 'Security lead who loves threat models and good encryption metaphors.', traits: ['careful','detail-driven','stern'], attitude: 'Quietly serious' },
      { displayName: 'Leo Ops', email: 'leo@ossguild.example', bio: 'Ops coordinator who keeps CI humming and deploys smooth.', traits: ['technical','reliable','methodical'], attitude: 'Rock-solid' },
      { displayName: 'Jay Intern', email: 'jay@ossguild.example', bio: 'Student intern learning best practices and coffee-run avoidance.', traits: ['eager','polite','busy'], attitude: 'Keen and polite' },
      { displayName: 'Grace Sponsor', email: 'grace@ossguild.example', bio: 'Sponsor liaison who builds bridges between industry and community.', traits: ['diplomatic','strategic','personable'], attitude: 'Connector' },
      { displayName: 'Lila Events', email: 'lila@ossguild.example', bio: 'Organizes hack nights with burritos and excellent name tags.', traits: ['energetic','organized','fun'], attitude: 'Lively host' },
      { displayName: 'Uma Podcast', email: 'uma@ossguild.example', bio: 'Interviews contributors and teases good stories out of PRs.', traits: ['curious','articulate','warm'], attitude: 'Curious storyteller' },
      { displayName: 'Anton ProjLead', email: 'anton@ossguild.example', bio: 'Starts new repos with big ideas and carefully named branches.', traits: ['ambitious','organized','friendly'], attitude: 'Ambitious builder' },
      { displayName: 'Mei A11y', email: 'mei@ossguild.example', bio: 'Accessibility advocate who delights in small, impactful fixes.', traits: ['empathetic','meticulous','supportive'], attitude: 'Principled and patient' },
      { displayName: 'Theo Mentor', email: 'theo@ossguild.example', bio: 'Runs office hours and pairs on hard debugging problems.', traits: ['patient','kind','consistent'], attitude: 'Dependable helper' },
      { displayName: 'Hana DocRev', email: 'hana@ossguild.example', bio: 'Documentation reviewer who leaves thorough and friendly comments.', traits: ['thorough','constructive','kind'], attitude: 'Helpful critic' },
      { displayName: 'Platform Admin', email: 'admin@ossguild.example', bio: 'Platform admin for the open-source community.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },

  {
    name: 'Harbor City Hawks',
    slug: 'harbor-hawks',
    description: 'Club for a local basketball team: rosters, practices, games, and fan engagement.',
    logoUrl: avatar('harbor-hawks'),
    bannerUrl: banner('Harbor City Hawks Banner'),
    channels: [
      { name: 'Team Announcements', type: 'public' },
      { name: 'Coaches', type: 'private' },
      { name: 'Players', type: 'private' },
      { name: 'Fans', type: 'public' },
      { name: 'Logistics', type: 'private' },
    ],
    users: [
      { displayName: 'Coach Ramirez', email: 'ramirez@harborhawks.example', bio: 'Head coach who brings discipline, pep talks, and the occasional clipboard flourish.', traits: ['strategic','encouraging','strict'], attitude: 'Driven and motivating' },
      { displayName: 'Coach Diaz', email: 'diaz@harborhawks.example', bio: 'Assistant coach who focuses on fundamentals and warm-ups with good playlists.', traits: ['observant','patient','firm'], attitude: 'Supportive and precise' },
      { displayName: 'Jordan Price', email: 'jordan@harborhawks.example', bio: 'Team captain, vocal leader and late-game clutch player.', traits: ['charismatic','disciplined','vocal'], attitude: 'Focused leader' },
      { displayName: 'Marcus Brown', email: 'marcus@harborhawks.example', bio: 'Starting guard with a fierce drive and a barber\'s precision haircut.', traits: ['athletic','focused','hungry'], attitude: 'Tenacious competitor' },
      { displayName: 'DeAndre Young', email: 'deandre@harborhawks.example', bio: 'Role player who does the small things that win games.', traits: ['team-first','steady','skilled'], attitude: 'Reliable and gritty' },
      { displayName: 'Ethan Bench', email: 'ethan@harborhawks.example', bio: 'Bench player ready to hustle and bring energy when called.', traits: ['eager','gritty','coachable'], attitude: 'Ready and eager' },
      { displayName: 'Dr. Kim (Physio)', email: 'kim@harborhawks.example', bio: 'Physio who patches up sprains and keeps the team mobile.', traits: ['calm','professional','kind'], attitude: 'Supportive professional' },
      { displayName: 'Sonia Manager', email: 'sonia@harborhawks.example', bio: 'Team manager who handles travel logistics and warm towels.', traits: ['organized','punctual','helpful'], attitude: 'Efficient organizer' },
      { displayName: 'Karen Parent', email: 'karen@harborhawks.example', bio: 'Parent rep who brings snacks and the loudest cheers.', traits: ['communicative','kind','supportive'], attitude: 'Enthusiastic supporter' },
      { displayName: 'Ivy Score', email: 'ivy@harborhawks.example', bio: 'Scorekeeper with impeccable stat sheets and calm thumbs.', traits: ['precise','quiet','reliable'], attitude: 'Meticulous and calm' },
      { displayName: 'Chris Photo', email: 'chris@harborhawks.example', bio: 'Photographer capturing slam dunks and celebratory high-fives.', traits: ['observant','creative','patient'], attitude: 'Energetic documentarian' },
      { displayName: 'Talia Fans', email: 'talia@harborhawks.example', bio: 'Fan club lead who organizes chants, banners, and themed nights.', traits: ['outgoing','enthusiastic','creative'], attitude: 'Loud and proud' },
      { displayName: 'Sam Kit', email: 'sam@harborhawks.example', bio: 'Kit manager who keeps jerseys crisp and laundry on schedule.', traits: ['tidy','resourceful','no-nonsense'], attitude: 'Practical and blunt' },
      { displayName: 'Ruth Volunteer', email: 'ruth@harborhawks.example', bio: 'Community volunteer who runs youth outreach and pizza distribution.', traits: ['giving','friendly','pragmatic'], attitude: 'Generous and practical' },
      { displayName: 'Nina Nutrition', email: 'nina@harborhawks.example', bio: 'Nutrition coach designing meal plans for peak performance.', traits: ['disciplined','supportive','knowledgeable'], attitude: 'Scientific and caring' },
      { displayName: 'Ben Analytics', email: 'ben@harborhawks.example', bio: 'Analyst who breaks down film and produces tidy charts.', traits: ['nerdy','precise','thorough'], attitude: 'Quietly obsessive' },
      { displayName: 'Ava Fitness', email: 'ava@harborhawks.example', bio: 'Conditioning coach who times sprints and offers grueling but effective circuits.', traits: ['energetic','strict','motivating'], attitude: 'Tough but encouraging' },
      { displayName: 'Liam Recruit', email: 'liam@harborhawks.example', bio: 'Tryout hopeful with high hopes and quick feet.', traits: ['nervous','excited','eager'], attitude: 'Determined rookie' },
      { displayName: 'Tom Alumni', email: 'tom@harborhawks.example', bio: 'Former player who shows up with stories and worn sneakers.', traits: ['nostalgic','supportive','experienced'], attitude: 'Fond veteran' },
      { displayName: 'Platform Admin', email: 'admin@harborhawks.example', bio: 'Platform admin for the team community.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },

  {
    name: 'Eagle High Book Club',
    slug: 'eagle-high-bookclub',
    description: 'Student-run book club with monthly picks, teacher advisors, and reading circles.',
    logoUrl: avatar('eagle-high-bookclub'),
    bannerUrl: banner('Eagle High Book Club Banner'),
    channels: [
      { name: 'Monthly Picks', type: 'public' },
      { name: 'Discussion Rooms', type: 'private' },
      { name: 'Teacher Advisors', type: 'private' },
      { name: 'Recommendations', type: 'public' },
      { name: 'Events', type: 'public' },
    ],
    users: [
      { displayName: 'Maya Chen', email: 'maya@eaglebook.example', bio: 'Club president who picks eclectic reads and brings thematic snacks.', traits: ['assertive','friendly','organized'], attitude: 'Curatorial and warm' },
      { displayName: 'Ethan Park', email: 'ethan@eaglebook.example', bio: 'Vice president who keeps logistics smooth and reminds people of deadlines.', traits: ['dependable','kind','organized'], attitude: 'Steady and calm' },
      { displayName: 'Hannah Lee', email: 'hannah@eaglebook.example', bio: 'Treasurer who will reconcile the bake sale numbers and keep the budget honest.', traits: ['meticulous','responsible','helpful'], attitude: 'Practical steward' },
      { displayName: 'Liam Zhou', email: 'liam@eaglebook.example', bio: 'Secretary who takes precise minutes and loves a good annotation.', traits: ['tidy','punctual','polite'], attitude: 'Organized and attentive' },
      { displayName: 'Ms. Thompson', email: 'thompson@eaglebook.example', bio: 'Teacher advisor who loves late-night book debates and brings cookies.', traits: ['wise','encouraging','patient'], attitude: 'Supportive mentor' },
      { displayName: 'Olivia Park', email: 'olivia@eaglebook.example', bio: 'Avid reader who always has a hot take and a dog-eared copy.', traits: ['curious','reflective','talkative'], attitude: 'Passionate and chatty' },
      { displayName: 'Marcus Bell', email: 'marcus@eaglebook.example', bio: 'Genre specialist who defends sci-fi like it\'s a spiritual practice.', traits: ['opinionated','fun','friendly'], attitude: 'Obsessive and charming' },
      { displayName: 'Sofia New', email: 'sofia@eaglebook.example', bio: 'First-time member eager to be pulled into lively discussion.', traits: ['shy','curious','polite'], attitude: 'Tentative and curious' },
      { displayName: 'Rosa Social', email: 'rosa@eaglebook.example', bio: 'Social media lead crafting witty posts and event promos.', traits: ['creative','proactive','witty'], attitude: 'Outgoing promoter' },
      { displayName: 'Mr. Keller', email: 'keller@eaglebook.example', bio: 'Event host who invites authors and organizes cozy Q&A nights.', traits: ['resourceful','organized','warm'], attitude: 'Hospitable and professional' },
      { displayName: 'Ben Snacks', email: 'ben@eaglebook.example', bio: 'Snack coordinator who pairs treats with the tone of the book.', traits: ['thoughtful','practical','kind'], attitude: 'Sweetly practical' },
      { displayName: 'Ava Reviewer', email: 'ava@eaglebook.example', bio: 'Writes concise and sharp reviews that stick to your ribs.', traits: ['critical','articulate','concise'], attitude: 'Wry critic' },
      { displayName: 'Ms. Brooks', email: 'brooks@eaglebook.example', bio: 'Librarian liaison who arranges reserves and shushes politely.', traits: ['helpful','methodical','friendly'], attitude: 'Warm and organized' },
      { displayName: 'Jordan Debate', email: 'jordan@eaglebook.example', bio: 'Moderates debates with fairness and a stopwatch.', traits: ['fair','calm','steady'], attitude: 'Even-handed and punctual' },
      { displayName: 'Grace Workshop', email: 'grace@eaglebook.example', bio: 'Leads writing workshops with kindness and sharp edits.', traits: ['creative','patient','encouraging'], attitude: 'Nurturing and incisive' },
      { displayName: 'Leo Photo', email: 'leo@eaglebook.example', bio: 'Documents meetings and the occasional dramatic reading.', traits: ['observant','creative','friendly'], attitude: 'Playful recorder' },
      { displayName: 'Alumni Sam', email: 'alumni@eaglebook.example', bio: 'Former leader who returns with author anecdotes and book-swap treasures.', traits: ['nostalgic','supportive','experienced'], attitude: 'Fond and generous' },
      { displayName: 'Iris Access', email: 'iris@eaglebook.example', bio: 'Accessibility rep ensuring meetings are welcoming and materials readable.', traits: ['empathetic','practical','thoughtful'], attitude: 'Attentive advocate' },
      { displayName: 'Parent Volunteer', email: 'parent@eaglebook.example', bio: 'Helps events and chaperones for evening meetings.', traits: ['friendly','organized','supportive'], attitude: 'Helpful and present' },
      { displayName: 'Platform Admin', email: 'admin@eaglebook.example', bio: 'Platform admin for the school book club.', traits: ['authoritative','helpful','omniscient'], attitude: 'Supportive admin' },
    ],
  },
];

export default TENANTS;
