-- AlterEnum
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TENANT_BRANDING_SOCIAL_LINK_CREATED';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TENANT_BRANDING_SOCIAL_LINK_UPDATED';
ALTER TYPE "ActionType" ADD VALUE IF NOT EXISTS 'TENANT_BRANDING_SOCIAL_LINK_DELETED';
